#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-robCompositions
Version  : 2.1.0
Release  : 24
URL      : https://cran.r-project.org/src/contrib/robCompositions_2.1.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/robCompositions_2.1.0.tar.gz
Summary  : Compositional Data Analysis
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-robCompositions-lib = %{version}-%{release}
Requires: R-NADA
Requires: R-abind
Requires: R-carData
Requires: R-data.table
Requires: R-diptest
Requires: R-e1071
Requires: R-flexmix
Requires: R-glue
Requires: R-laeken
Requires: R-modeltools
Requires: R-mvtnorm
Requires: R-pcaPP
Requires: R-prabclus
Requires: R-ranger
Requires: R-rio
Requires: R-tidyr
Requires: R-trimcluster
Requires: R-truncnorm
Requires: R-vcd
Requires: R-zCompositions
Requires: R-zoo
BuildRequires : R-GGally
BuildRequires : R-NADA
BuildRequires : R-VIM
BuildRequires : R-abind
BuildRequires : R-carData
BuildRequires : R-cvTools
BuildRequires : R-data.table
BuildRequires : R-diptest
BuildRequires : R-e1071
BuildRequires : R-flexmix
BuildRequires : R-fpc
BuildRequires : R-glue
BuildRequires : R-kernlab
BuildRequires : R-laeken
BuildRequires : R-mclust
BuildRequires : R-modeltools
BuildRequires : R-mvtnorm
BuildRequires : R-pcaPP
BuildRequires : R-pls
BuildRequires : R-prabclus
BuildRequires : R-ranger
BuildRequires : R-rio
BuildRequires : R-robustbase
BuildRequires : R-rrcov
BuildRequires : R-sROC
BuildRequires : R-tidyr
BuildRequires : R-trimcluster
BuildRequires : R-truncnorm
BuildRequires : R-vcd
BuildRequires : R-zCompositions
BuildRequires : R-zoo
BuildRequires : buildreq-R

%description
{robCompositions}
=======================================
Robust Methods for Compositional Data

%package lib
Summary: lib components for the R-robCompositions package.
Group: Libraries

%description lib
lib components for the R-robCompositions package.


%prep
%setup -q -c -n robCompositions

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555411348

%install
export SOURCE_DATE_EPOCH=1555411348
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library robCompositions
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library robCompositions
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library robCompositions
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc robCompositions || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/robCompositions/CITATION
/usr/lib64/R/library/robCompositions/DESCRIPTION
/usr/lib64/R/library/robCompositions/INDEX
/usr/lib64/R/library/robCompositions/Meta/Rd.rds
/usr/lib64/R/library/robCompositions/Meta/data.rds
/usr/lib64/R/library/robCompositions/Meta/features.rds
/usr/lib64/R/library/robCompositions/Meta/hsearch.rds
/usr/lib64/R/library/robCompositions/Meta/links.rds
/usr/lib64/R/library/robCompositions/Meta/nsInfo.rds
/usr/lib64/R/library/robCompositions/Meta/package.rds
/usr/lib64/R/library/robCompositions/Meta/vignette.rds
/usr/lib64/R/library/robCompositions/NAMESPACE
/usr/lib64/R/library/robCompositions/NEWS
/usr/lib64/R/library/robCompositions/R/robCompositions
/usr/lib64/R/library/robCompositions/R/robCompositions.rdb
/usr/lib64/R/library/robCompositions/R/robCompositions.rdx
/usr/lib64/R/library/robCompositions/data/Rdata.rdb
/usr/lib64/R/library/robCompositions/data/Rdata.rds
/usr/lib64/R/library/robCompositions/data/Rdata.rdx
/usr/lib64/R/library/robCompositions/doc/checkenc.sh
/usr/lib64/R/library/robCompositions/doc/gm.cpp
/usr/lib64/R/library/robCompositions/doc/imputation.R
/usr/lib64/R/library/robCompositions/doc/imputation.Rnw
/usr/lib64/R/library/robCompositions/doc/imputation.pdf
/usr/lib64/R/library/robCompositions/doc/index.html
/usr/lib64/R/library/robCompositions/doc/robCompositions-overview.Rnw
/usr/lib64/R/library/robCompositions/doc/robCompositions-overview.pdf
/usr/lib64/R/library/robCompositions/doc/test.sh
/usr/lib64/R/library/robCompositions/doc/writecsvs.R
/usr/lib64/R/library/robCompositions/help/AnIndex
/usr/lib64/R/library/robCompositions/help/aliases.rds
/usr/lib64/R/library/robCompositions/help/paths.rds
/usr/lib64/R/library/robCompositions/help/robCompositions.rdb
/usr/lib64/R/library/robCompositions/help/robCompositions.rdx
/usr/lib64/R/library/robCompositions/html/00Index.html
/usr/lib64/R/library/robCompositions/html/R.css
/usr/lib64/R/library/robCompositions/tests/imp_test.R
/usr/lib64/R/library/robCompositions/tests/importFood.R
/usr/lib64/R/library/robCompositions/tests/rz.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/robCompositions/libs/robCompositions.so
